name: CompatHelper

on:
  schedule:
    - cron: '00 00 * * 1'
  workflow_dispatch:

jobs:
  compat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: JuliaRegistries/CompatHelper.jl@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
